# Generated by Django 3.1.4 on 2021-01-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('extradition', 'Выдача'), ('pass', 'Сдача')], max_length=20, null=True, verbose_name='Тип акта')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер акта')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Акт передачи')),
                ('date', models.DateField(verbose_name='Дата передачи')),
                ('printer', models.ManyToManyField(to='print.Printer', verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Акт передачи принтера',
                'verbose_name_plural': 'Акты передачи принтеров',
            },
        ),
        migrations.CreateModel(
            name='CatrigeAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('extradition', 'Выдача'), ('pass', 'Сдача')], max_length=20, null=True, verbose_name='Тип акта')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер акта')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Акт передачи')),
                ('date', models.DateField(verbose_name='Дата передачи')),
                ('catrige', models.ManyToManyField(to='print.Cartridge', verbose_name='Картридж')),
            ],
            options={
                'verbose_name': 'Акт передачи картриджа',
                'verbose_name_plural': 'Акты передачи картриджей',
            },
        ),
    ]
