# Generated by Django 3.1.4 on 2021-01-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0002_catrigeact_printeract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='date',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='date',
        ),
    ]
