# Generated by Django 3.1.4 on 2021-01-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0003_auto_20210107_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='location',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='printerschedule',
            name='location',
        ),
    ]
