# Generated by Django 3.1.4 on 2021-01-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210107_1654'),
        ('print', '0004_auto_20210107_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Место расположение'),
        ),
        migrations.AddField(
            model_name='printerschedule',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Место расположение'),
            preserve_default=False,
        ),
    ]
