# Generated by Django 3.1.4 on 2021-01-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0006_cartridge_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип принтера',
                'verbose_name_plural': 'Типы принтеров',
            },
        ),
        migrations.RemoveField(
            model_name='printermodel',
            name='type',
        ),
    ]
