# Generated by Django 3.1.4 on 2021-01-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0007_auto_20210108_0106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='PrinterType',
        ),
    ]
