# Generated by Django 3.1.4 on 2021-01-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0008_auto_20210108_0109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrinterType',
            new_name='Type',
        ),
        migrations.AddField(
            model_name='printermodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='print.type', verbose_name='Тип принтера'),
        ),
    ]
