# Generated by Django 3.1.4 on 2021-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0009_auto_20210108_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='cartridge',
            field=models.ManyToManyField(blank=True, null=True, to='print.Cartridge', verbose_name='Установленые картриджи'),
        ),
    ]
