# Generated by Django 3.1.4 on 2021-01-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0011_auto_20210108_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='location',
        ),
    ]
