# Generated by Django 3.1.4 on 2021-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0012_remove_cartridge_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerschedule',
            name='to_perform',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
