# Generated by Django 3.1.4 on 2021-01-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0013_printerschedule_to_perform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerschedule',
            name='to_perform',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Работы выполнены'),
        ),
        migrations.CreateModel(
            name='PrinterApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер заявки')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(verbose_name='Выполнена')),
                ('printerShedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.printerschedule', verbose_name='Заявка из журнала')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
