# Generated by Django 3.1.4 on 2021-01-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0014_auto_20210115_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerapp',
            name='number',
        ),
    ]
