# Generated by Django 3.1.4 on 2021-01-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0015_remove_printerapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerschedule',
            name='to_perform',
        ),
    ]
