# Generated by Django 3.1.4 on 2021-01-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0016_remove_printerschedule_to_perform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerapp',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
    ]
