# Generated by Django 3.1.4 on 2020-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workNumber', models.CharField(max_length=12, verbose_name='Рабочий номер')),
                ('mobileNumber', models.CharField(blank=True, max_length=12, verbose_name='Мобильный номер телефона')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'db_table': 'Telephone',
            },
        ),
        migrations.RenameModel(
            old_name='Act',
            new_name='Acts',
        ),
    ]
