# Generated by Django 3.1.4 on 2020-12-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название должности')),
                ('telephone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('lastName', models.CharField(max_length=50, verbose_name='Имя')),
                ('fatherName', models.CharField(max_length=50, verbose_name='Отчество')),
                ('workTelephone', models.CharField(blank=True, max_length=15, verbose_name='Внутрений номер')),
                ('mobileTelephone', models.CharField(blank=True, max_length=15, verbose_name='Мобильный телефон')),
                ('department', models.ManyToManyField(to='personal.Department', verbose_name='Отдел')),
                ('posts', models.ManyToManyField(to='personal.Post', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
