# Generated by Django 3.1.4 on 2021-01-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('lastName', models.CharField(max_length=50, verbose_name='Имя')),
                ('fatherName', models.CharField(max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Эл.почта')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('workTelephone', models.CharField(max_length=15, verbose_name='Внутрений номер')),
                ('mobileTelephone', models.CharField(max_length=15, verbose_name='Мобильный телефон')),
                ('isVip', models.BooleanField(default=False, verbose_name='Высшее руководство')),
                ('department', models.ManyToManyField(to='personal.Department', verbose_name='Отдел')),
                ('posts', models.ManyToManyField(to='personal.Post', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
