# Generated by Django 3.1.4 on 2021-01-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='room',
        ),
    ]
