# Generated by Django 3.1.4 on 2021-01-06 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0006_delete_acts'),
        ('locations', '0002_auto_20201219_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActWorkSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('extradition', 'Выдача'), ('pass', 'Сдача')], max_length=20, null=True, verbose_name='Тип акта')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер акта')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Акт передачи')),
                ('date', models.DateField(verbose_name='Дата передачи')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Операционная система')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
            },
        ),
        migrations.CreateModel(
            name='PCModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название модели')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Модель системного блока',
                'verbose_name_plural': 'Модели системных блоков',
            },
        ),
        migrations.CreateModel(
            name='StatusWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='WorkSpaceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apper', models.CharField(max_length=100, unique=True, verbose_name='Номер заявки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.actworkspace', verbose_name='Номер акта')),
            ],
            options={
                'verbose_name': 'Журнал выдачи рабочего места',
                'verbose_name_plural': 'Журналы выдачи рабочих мест',
            },
        ),
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название модели')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель Токена',
                'verbose_name_plural': 'Модели токенов',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата передачи')),
                ('serialNumber', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Месторасположение')),
                ('tokenModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.tokenmodel', verbose_name='Модель токена')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.CreateModel(
            name='TelephoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название модели')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель телефона',
                'verbose_name_plural': 'Модели телефонов',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата передачи')),
                ('serialNumber', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Месторасположение')),
                ('modelTelephone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.telephonemodel', verbose_name='Модель телефона')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='PowerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название модели')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель источника бесперебойного питания',
                'verbose_name_plural': 'Модели источников бесперебойного питания',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата передачи')),
                ('serialNumber', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Месторасположение')),
                ('powerModel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.telephonemodel', verbose_name='Модель источника бесперебойного писатния')),
            ],
            options={
                'verbose_name': 'Источник бесперебойного питания',
                'verbose_name_plural': 'Истоники бесперебойного питания',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата передачи')),
                ('serialNumber', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('name', models.CharField(max_length=100, verbose_name='Имя компьютера')),
                ('HDD', models.IntegerField(blank=True, null=True, verbose_name='Жесктий диск')),
                ('RAM', models.IntegerField(blank=True, null=True, verbose_name='Оперативная память')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Месторасположение')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.statuswork', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Системный блок',
                'verbose_name_plural': 'Системные блоки',
            },
        ),
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название модели')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('diagonal', models.IntegerField(blank=True, verbose_name='Диагональ')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель мониторов',
                'verbose_name_plural': 'Модели мониторов',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата передачи')),
                ('serialNumber', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Месторасположение')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.monitormodel', verbose_name='Модель')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.statuswork', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Монитор',
                'verbose_name_plural': 'Мониторы',
            },
        ),
        migrations.AddField(
            model_name='actworkspace',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.monitor', verbose_name='Монитор'),
        ),
        migrations.AddField(
            model_name='actworkspace',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.pc', verbose_name='Системный блок'),
        ),
        migrations.AddField(
            model_name='actworkspace',
            name='power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.power', verbose_name='Источник бесперебойного питания'),
        ),
        migrations.AddField(
            model_name='actworkspace',
            name='telephone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.telephone', verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='actworkspace',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.token', verbose_name='Токен'),
        ),
    ]
