# Generated by Django 3.1.4 on 2021-01-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_persons'),
        ('workspace', '0002_auto_20210107_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='actworkspace',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.persons', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
