# Generated by Django 3.1.4 on 2021-01-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_actworkspace_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='location',
        ),
        migrations.RemoveField(
            model_name='power',
            name='location',
        ),
        migrations.RemoveField(
            model_name='telephone',
            name='location',
        ),
        migrations.RemoveField(
            model_name='token',
            name='location',
        ),
    ]
