# Generated by Django 3.1.4 on 2021-01-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_auto_20210107_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='location',
        ),
        migrations.RemoveField(
            model_name='power',
            name='location',
        ),
        migrations.RemoveField(
            model_name='telephone',
            name='location',
        ),
        migrations.RemoveField(
            model_name='token',
            name='location',
        ),
    ]
