# Generated by Django 3.1.4 on 2020-12-18 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя в локальной сети')),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модели принтеров',
                'db_table': 'PrinterModel',
            },
        ),
        migrations.CreateModel(
            name='PrinterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус принтера',
                'verbose_name_plural': 'Статусы принтеров',
                'db_table': 'PrinterStatus',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя в локальной сети')),
                ('isColor', models.BooleanField(default=True, verbose_name='Цветной')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 21, 23, 13, 876856))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Проиводитель')),
                ('printerLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Местораспложение')),
                ('printerModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printermodel', verbose_name='Модель')),
                ('printerStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printerstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'db_table': 'Printer',
            },
        ),
    ]
