# Generated by Django 3.1.4 on 2020-12-18 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 21, 24, 22, 422547)),
        ),
    ]
