# Generated by Django 3.1.4 on 2020-12-18 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_auto_20201219_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='discription',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 19, 0, 26, 7, 142883)),
        ),
    ]
