# Generated by Django 3.1.4 on 2020-12-18 21:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0008_auto_20201219_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 19, 0, 48, 5, 68903)),
        ),
        migrations.CreateModel(
            name='PrinterAplictaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер заявки')),
                ('discriptions', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printer', verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Заявка на обслуживание принтера',
                'verbose_name_plural': 'Заявки на обслуживание принтеры',
            },
        ),
    ]
