# Generated by Django 3.1.4 on 2020-12-18 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0009_auto_20201219_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printeraplictaion',
            options={'verbose_name': 'Заявка на обслуживание принтера', 'verbose_name_plural': 'Заявки на обслуживание принтеров'},
        ),
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 19, 0, 53, 39, 40642)),
        ),
    ]
