# Generated by Django 3.1.4 on 2020-12-18 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0010_auto_20201219_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 19, 1, 5, 59, 783741)),
        ),
    ]
