# Generated by Django 3.1.4 on 2020-12-18 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0015_auto_20201219_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 1, 19, 49, 960605)),
        ),
    ]
