# Generated by Django 3.1.4 on 2020-12-19 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0017_auto_20201219_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 12, 57, 29, 654000)),
        ),
        migrations.AlterField(
            model_name='printeraplictaion',
            name='number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер заявки'),
        ),
    ]
