# Generated by Django 3.1.4 on 2020-12-19 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0018_auto_20201219_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='printeraplictaion',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Выполнена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 13, 11, 27, 388309)),
        ),
    ]
