# Generated by Django 3.1.4 on 2020-12-19 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0019_auto_20201219_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 13, 15, 12, 300573)),
        ),
        migrations.RemoveField(
            model_name='printeraplictaion',
            name='printer',
        ),
        migrations.AddField(
            model_name='printeraplictaion',
            name='printer',
            field=models.ManyToManyField(to='printers.Printer', verbose_name='Серийный номер'),
        ),
    ]
