# Generated by Django 3.1.4 on 2020-12-19 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0020_auto_20201219_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 13, 16, 13, 578445)),
        ),
    ]
