# Generated by Django 3.1.4 on 2020-12-21 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0021_auto_20201219_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 21, 17, 32, 31, 514703)),
        ),
    ]
