# Generated by Django 3.1.4 on 2020-12-21 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0022_auto_20201221_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 21, 17, 38, 37, 276114)),
        ),
    ]
