# Generated by Django 3.1.4 on 2020-12-21 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0023_auto_20201221_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 21, 17, 46, 2, 772315)),
        ),
    ]
