# Generated by Django 3.1.4 on 2020-12-26 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0024_auto_20201221_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 26, 16, 6, 9, 858741)),
        ),
    ]
