# Generated by Django 3.1.4 on 2020-12-26 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0027_auto_20201226_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='date',
        ),
        migrations.AddField(
            model_name='printer',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2020, 12, 26, 16, 8, 30, 972651)),
        ),
    ]
