# Generated by Django 3.1.4 on 2020-12-26 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0030_auto_20201226_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 26, 16, 18, 25, 44667)),
        ),
    ]
