# Generated by Django 3.1.4 on 2020-12-26 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0033_auto_20201226_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 26, 13, 22, 11, 864982, tzinfo=utc)),
        ),
    ]
