# Generated by Django 3.1.4 on 2020-12-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_acts'),
        ('locations', '0002_auto_20201219_0024'),
        ('printers', '0035_auto_20201226_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Прозводитель'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printerLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Месторасположение'),
        ),
        migrations.CreateModel(
            name='PrinterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apper', models.CharField(max_length=100, unique=True, verbose_name='Номер заявки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printer', verbose_name='Принтер')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Место расположение')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printerstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Журнал принтера',
                'verbose_name_plural': 'Журналы принтеров',
            },
        ),
    ]
