# Generated by Django 3.1.4 on 2020-12-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0037_auto_20201227_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printeract',
            name='serialNumber',
            field=models.ManyToManyField(to='printers.Printer', verbose_name='Серийный номер'),
        ),
    ]
