# Generated by Django 3.1.4 on 2020-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0038_auto_20201227_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='date_create',
        ),
        migrations.AddField(
            model_name='printerschedule',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
    ]
