# Generated by Django 3.1.4 on 2020-12-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0039_auto_20201227_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='printerschedule',
            name='date_create',
        ),
    ]
