# Generated by Django 3.1.4 on 2020-12-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0040_auto_20201227_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='ip',
            field=models.CharField(default=1, max_length=15, verbose_name='ip-адрес'),
            preserve_default=False,
        ),
    ]
