# Generated by Django 3.1.4 on 2020-12-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0041_printer_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='ip',
            field=models.CharField(blank=True, max_length=15, verbose_name='ip-адрес'),
        ),
    ]
