# Generated by Django 3.1.4 on 2021-01-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210107_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер титула')),
                ('name', models.CharField(max_length=100, verbose_name='Название титула')),
            ],
            options={
                'verbose_name': 'Титул',
                'verbose_name_plural': 'Титулы',
                'db_table': 'Titul',
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='titulName',
        ),
        migrations.AlterField(
            model_name='room',
            name='titul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.titul', verbose_name='Титул'),
        ),
    ]
