# Generated by Django 3.1.4 on 2021-01-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_remove_post_room'),
        ('locations', '0004_auto_20210107_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.department', verbose_name='Отдел'),
        ),
    ]
