# Generated by Django 3.1.4 on 2020-12-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('printers', '0002_auto_20201218_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatrigeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус картриджа',
                'verbose_name_plural': 'Статусы картриджей',
                'db_table': 'CatrigeStatus',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Цвет')),
                ('word', models.CharField(max_length=1, verbose_name='Обозначение')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='CatrigeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название модели')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Модель картриджа',
                'verbose_name_plural': 'Модели картриджей',
            },
        ),
        migrations.CreateModel(
            name='Catrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('original', models.BooleanField(verbose_name='Оригинальный')),
                ('CatrigeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.catrigemodel', verbose_name='Модель картриджа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catriges', to='printers.printer', verbose_name='Установлен в принтере')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.catrigestatus', verbose_name='Статус картриджа')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': ' Картриджи',
                'db_table': 'Catrige',
            },
        ),
    ]
