# Generated by Django 3.1.4 on 2020-12-18 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catrige',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 18, 21, 40, 46, 831120)),
        ),
    ]
