# Generated by Django 3.1.4 on 2020-12-18 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0007_auto_20201219_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catrige',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 19, 0, 48, 5, 76423)),
        ),
    ]
