# Generated by Django 3.1.4 on 2020-12-18 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0012_auto_20201219_0110'),
        ('mainapp', '0001_initial'),
        ('catriges', '0008_auto_20201219_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('original', models.BooleanField(verbose_name='Оригинальный')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 12, 19, 1, 10, 20, 398782), null=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': ' Картриджи',
                'db_table': 'Cartridge',
            },
        ),
        migrations.RenameModel(
            old_name='CatrigeModel',
            new_name='CartridgeModel',
        ),
        migrations.DeleteModel(
            name='Catrige',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='CartridgeModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.cartridgemodel', verbose_name='Модель картриджа'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridges', to='printers.printer', verbose_name='Установлен в принтере'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.catrigestatus', verbose_name='Статус картриджа'),
        ),
    ]
