# Generated by Django 3.1.4 on 2020-12-18 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0009_auto_20201219_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 19, 1, 11, 2, 499171), null=True),
        ),
        migrations.CreateModel(
            name='CartridgeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер заявки')),
                ('discriptions', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.cartridge', verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Заявка на обслуживание картриджа',
                'verbose_name_plural': 'Заявки на обслуживание картриджей',
            },
        ),
    ]
