# Generated by Django 3.1.4 on 2020-12-18 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0010_auto_20201219_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 19, 1, 15, 59, 544751), null=True),
        ),
    ]
