# Generated by Django 3.1.4 on 2020-12-19 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0013_auto_20201219_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartridgeapplication',
            old_name='discriptions',
            new_name='descriptions',
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 12, 53, 18, 97892)),
        ),
    ]
