# Generated by Django 3.1.4 on 2020-12-19 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0017_auto_20201219_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 13, 16, 13, 584464)),
        ),
        migrations.RemoveField(
            model_name='cartridgeapplication',
            name='cartridge',
        ),
        migrations.AddField(
            model_name='cartridgeapplication',
            name='cartridge',
            field=models.ManyToManyField(to='catriges.Cartridge', verbose_name='Серийный номер'),
        ),
    ]
