# Generated by Django 3.1.4 on 2020-12-26 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0028_auto_20201226_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='date',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
