# Generated by Django 3.1.4 on 2020-12-27 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('printers', '0038_auto_20201227_1138'),
        ('catriges', '0030_auto_20201226_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер акта')),
                ('file', models.FileField(upload_to='', verbose_name='Акт передачи')),
                ('date', models.DateField(verbose_name='Дата передачи')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person', verbose_name='Пользователь')),
                ('serialNumber', models.ManyToManyField(to='printers.Printer', verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Акт передачи принтера',
                'verbose_name_plural': 'Акты передачи принтеров',
            },
        ),
    ]
