# Generated by Django 3.1.4 on 2020-12-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0031_cartridgeact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='description',
        ),
    ]
