# Generated by Django 3.1.4 on 2020-12-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0032_auto_20201227_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apper', models.CharField(max_length=100, unique=True, verbose_name='Номер заявки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('catrige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.cartridge', verbose_name='Картридж')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.catrigestatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Журнал картриджа',
                'verbose_name_plural': 'Журналы картриджей',
            },
        ),
    ]
